# Generated by Django 2.2.4 on 2019-08-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('first_login', models.DateTimeField(verbose_name='f_log')),
                ('last_login', models.DateTimeField(verbose_name='l_log')),
                ('another', models.TextField()),
            ],
        ),
    ]
