# Generated by Django 2.2.4 on 2019-08-20 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='number')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('contents', models.CharField(max_length=300)),
                ('writer', models.CharField(max_length=100, verbose_name='writer')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DormantUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLogin', models.DateTimeField(blank=True)),
                ('dormantDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleteDate', models.DateTimeField(blank=True)),
                ('checkNotice', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(blank=True, max_length=100, verbose_name='check')),
                ('dormant_cnt', models.IntegerField(default=0, verbose_name='dormant_cnt')),
                ('memo', models.TextField(max_length=300, verbose_name='memo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
