# Generated by Django 2.2.4 on 2019-08-26 05:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='number')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('contents', models.CharField(max_length=300)),
                ('writer', models.CharField(max_length=100, verbose_name='writer')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2019, 8, 26, 5, 30, 18, 117448, tzinfo=utc))),
                ('last_edit', models.DateTimeField(default=datetime.datetime(2019, 8, 26, 5, 30, 18, 164312, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='DormantUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='username')),
                ('role_dormant', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Business'), (2, 'Customer')], null=True)),
                ('last_login', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 26, 5, 30, 18, 164312, tzinfo=utc))),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='이메일')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='핸드폰 번호')),
                ('memo', models.TextField(blank=True, max_length=1000, verbose_name='memo')),
                ('dormant_date', models.DateTimeField(default=datetime.datetime(2019, 8, 26, 5, 30, 18, 164312, tzinfo=utc))),
                ('delete_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 26, 5, 30, 18, 164312, tzinfo=utc))),
                ('check_notice', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='사업장 이름')),
                ('business_number', models.IntegerField(blank=True, null=True, verbose_name='사업자 번호')),
                ('star_point', models.IntegerField(blank=True, null=True, verbose_name='보유 별')),
                ('kakao_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='카카오톡 아이디')),
                ('mining_point', models.IntegerField(blank=True, null=True, verbose_name='보유 포인트')),
            ],
            options={
                'verbose_name_plural': '휴면 계정',
            },
        ),
        migrations.CreateModel(
            name='UserC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.CharField(max_length=100, verbose_name='카카오톡 아이디')),
                ('mining_point', models.IntegerField(default=0, verbose_name='보유 포인트')),
                ('user_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '커스텀 사용자',
            },
        ),
        migrations.CreateModel(
            name='UserB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='사업장 이름')),
                ('business_number', models.IntegerField(verbose_name='사업자 번호')),
                ('star_point', models.IntegerField(default=0, verbose_name='보유 별')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '비즈니스 사용자',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_profile', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Business'), (2, 'Customer')], null=True, verbose_name='사용자 유형')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='이메일')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='핸드폰 번호')),
                ('dormant_cnt', models.IntegerField(default=0, verbose_name='휴면전환 남은 일자')),
                ('memo', models.TextField(blank=True, max_length=1000, verbose_name='Memo')),
                ('check_alert', models.BooleanField(blank=True, default=False, verbose_name='사전알림 여부')),
                ('conversion_check', models.BooleanField(blank=True, default=False, verbose_name='휴면전환 60전')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
