# Generated by Django 2.2.4 on 2019-08-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check_alert',
            field=models.BooleanField(default=False),
        ),
    ]
