# Generated by Django 2.2.4 on 2019-08-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormantuserinfo',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, verbose_name='memo'),
        ),
    ]
