# Generated by Django 2.2.4 on 2019-08-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='핸드폰 번호'),
        ),
    ]
