# Generated by Django 2.2.4 on 2019-08-21 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormantuserinfo',
            name='checkNotice',
        ),
        migrations.RemoveField(
            model_name='dormantuserinfo',
            name='deleteDate',
        ),
        migrations.RemoveField(
            model_name='dormantuserinfo',
            name='dormantDate',
        ),
        migrations.RemoveField(
            model_name='dormantuserinfo',
            name='lastLogin',
        ),
        migrations.RemoveField(
            model_name='dormantuserinfo',
            name='role_dormant',
        ),
        migrations.RemoveField(
            model_name='dormantuserinfo',
            name='username',
        ),
    ]
