# Generated by Django 2.2.4 on 2019-08-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormantuserinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='핸드폰 번호'),
        ),
    ]
