# Generated by Django 2.2.4 on 2019-08-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='check_alert',
            field=models.BooleanField(blank=True, default=False, verbose_name='check_alter'),
        ),
    ]
