# Generated by Django 2.2.4 on 2019-08-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pwd',
            field=models.CharField(default='0000', max_length=20, verbose_name='pwd'),
        ),
    ]
