# Generated by Django 2.2.4 on 2019-08-21 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='deleteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 1, 49, 56, 722268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='lastLogin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 1, 49, 56, 722268, tzinfo=utc)),
        ),
    ]
