# Generated by Django 2.2.4 on 2019-08-20 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_profile_check_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormantuserinfo',
            name='checkNotice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='role_dormant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Business'), (2, 'Customer')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='핸드폰 번호'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role_profile',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Business'), (2, 'Customer')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='check_alert',
            field=models.BooleanField(blank=True, default=False, verbose_name='check_alter'),
        ),
        migrations.CreateModel(
            name='UserC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_Id', models.CharField(max_length=100, verbose_name='카카오톡 아이디')),
                ('mining_point', models.IntegerField(default=0, verbose_name='보유 포인트')),
                ('user_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='사업장 이름')),
                ('business_number', models.IntegerField(verbose_name='사업자 번호')),
                ('star_point', models.IntegerField(default=0, verbose_name='보유 포인트')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
