# Generated by Django 2.2.4 on 2019-08-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190821_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='핸드폰 번호'),
        ),
    ]
