# Generated by Django 2.2.4 on 2019-08-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='num')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('contents', models.TextField()),
            ],
        ),
    ]
