# Generated by Django 2.2.4 on 2019-08-21 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190821_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dormantuserinfo',
            options={'verbose_name_plural': '휴면 계정'},
        ),
        migrations.AlterModelOptions(
            name='userb',
            options={'verbose_name_plural': '비즈니스 사용자'},
        ),
        migrations.AlterModelOptions(
            name='userc',
            options={'verbose_name_plural': '커스텀 사용자'},
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='business_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='사업자 번호'),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사업장 이름'),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='kakao_Id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='카카오톡 아이디'),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='mining_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='보유 포인트'),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='star_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='보유 포인트'),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='deleteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 3, 20, 5, 759887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='lastLogin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 3, 20, 5, 759887, tzinfo=utc)),
        ),
    ]
