# Generated by Django 2.2.4 on 2019-08-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190820_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormantuserinfo',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='memo',
            field=models.TextField(blank=True, max_length=300, verbose_name='memo'),
        ),
    ]
