# Generated by Django 2.2.4 on 2019-08-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190822_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='check',
        ),
    ]
