# Generated by Django 2.2.4 on 2019-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190821_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dormantNotice_day_filter',
            field=models.BooleanField(blank=True, default=False, verbose_name='dormantNotice_day_filter'),
        ),
    ]
