# Generated by Django 2.2.4 on 2019-08-21 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190821_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormantuserinfo',
            name='checkNotice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='deleteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 1, 13, 22, 873775, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='dormantDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='lastLogin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 1, 13, 22, 873775, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='role_dormant',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Business'), (2, 'Customer')], null=True),
        ),
        migrations.AddField(
            model_name='dormantuserinfo',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='username'),
        ),
    ]
