# Generated by Django 2.2.4 on 2019-08-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190827_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='last_edit',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='delete_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='dormant_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
