# Generated by Django 2.2.4 on 2019-08-21 03:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190821_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='deleteDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 3, 28, 32, 498812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='lastLogin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 21, 3, 28, 32, 498812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='star_point',
            field=models.IntegerField(blank=True, null=True, verbose_name='보유 별'),
        ),
        migrations.AlterField(
            model_name='userb',
            name='star_point',
            field=models.IntegerField(default=0, verbose_name='보유 별'),
        ),
    ]
