# Generated by Django 2.2.4 on 2019-08-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contents',
            new_name='Content',
        ),
    ]
