# Generated by Django 2.2.4 on 2019-08-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190807_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.TextField(verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='content',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='number'),
        ),
    ]
