# Generated by Django 2.2.4 on 2019-08-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190827_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='핸드폰 번호'),
        ),
    ]
