# Generated by Django 2.2.4 on 2019-08-27 03:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190827_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_joined',
            field=models.DateTimeField(default=app.models.Content.date_joined_korean_time),
        ),
        migrations.AlterField(
            model_name='content',
            name='last_edit',
            field=models.DateTimeField(default=app.models.Content.last_edit_korean_time),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='delete_date',
            field=models.DateTimeField(blank=True, default=app.models.DormantUserInfo.delete_date_korean_time),
        ),
        migrations.AlterField(
            model_name='dormantuserinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, default=app.models.DormantUserInfo.last_login_korean_time),
        ),
    ]
