# Generated by Django 2.2.4 on 2019-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190807_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.TextField(default='test'),
        ),
    ]
