# Generated by Django 2.2.4 on 2019-08-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190807_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.TextField(),
        ),
    ]
