# Generated by Django 2.2.4 on 2019-08-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190807_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='contents',
            field=models.CharField(max_length=300),
        ),
    ]
