# Generated by Django 2.2.4 on 2019-08-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190807_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='content',
            name='writer',
            field=models.CharField(default='test', max_length=100, verbose_name='writer'),
        ),
    ]
