# Generated by Django 2.2.4 on 2019-08-12 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190808_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='content',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
