# Generated by Django 2.2.4 on 2019-08-14 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dormant_count',
        ),
        migrations.AlterField(
            model_name='content',
            name='last_edit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='nickname'),
        ),
    ]
