# Generated by Django 2.2.4 on 2019-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profile_dormant_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='check',
            field=models.CharField(blank=True, max_length=100, verbose_name='check'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dormant_cnt',
            field=models.IntegerField(default=0, verbose_name='dormant_cnt'),
        ),
    ]
