# Generated by Django 2.2.4 on 2019-08-16 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190814_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormantUserB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='이메일')),
                ('businessNumber', models.IntegerField(max_length=11, verbose_name='핸드폰 번호')),
                ('phoneNumber', models.IntegerField(max_length=15, verbose_name='핸드폰 번호')),
                ('name', models.CharField(max_length=100, verbose_name='ID')),
                ('point', models.IntegerField(max_length=100000, verbose_name='보유 포인트')),
            ],
        ),
        migrations.CreateModel(
            name='DormantUserC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='이메일')),
                ('kakaoId', models.CharField(max_length=100, verbose_name='카카오톡 아이디')),
                ('phoneNumber', models.IntegerField(max_length=15, verbose_name='핸드폰 번호')),
                ('name', models.CharField(max_length=100, verbose_name='ID')),
                ('point', models.IntegerField(max_length=100000, verbose_name='보유 포인트')),
            ],
        ),
        migrations.CreateModel(
            name='DormantUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLogin', models.DateTimeField(blank=True)),
                ('dormantDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleteDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='memo',
            field=models.CharField(blank=True, max_length=1000, verbose_name='memo'),
        ),
    ]
