# Generated by Django 2.2.4 on 2019-08-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190816_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='memo',
            field=models.TextField(max_length=300, verbose_name='memo'),
        ),
    ]
