# Generated by Django 2.2.4 on 2019-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_dormantuserb_dormantuserc_dormantuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormantuserinfo',
            name='checkNotice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Business'), (2, 'Customer')], null=True),
        ),
        migrations.AlterField(
            model_name='dormantuserb',
            name='businessNumber',
            field=models.IntegerField(max_length=11, verbose_name='사업자 번호'),
        ),
    ]
