# Generated by Django 2.2.4 on 2019-08-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190816_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=0, max_length=100000, verbose_name='보유 포인트'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='memo',
            field=models.TextField(blank=True, max_length=300, verbose_name='memo'),
        ),
    ]
