# Generated by Django 2.2.4 on 2019-08-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190819_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='point',
        ),
        migrations.AlterField(
            model_name='profile',
            name='memo',
            field=models.TextField(max_length=300, verbose_name='memo'),
        ),
    ]
